"use client";

import { useParams } from "next/navigation";
import Navigation from "@/app/components/navigation";
import Footer from "@/app/components/footer";
import Image from "next/image";
import { useState } from "react";
import {Button} from "@/components/ui/button";

const blogs = [
  { 
    id: 1, 
    name: "Back to Fiction: Wha i`m Reading This Summer", 
    description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.", 
    year: "Mar 23, 2023",
    image: "/img-1.jpg"
  },  
  { 
        id: 2, 
        name: "Do Not Leave Tokyo Before Eating This Ramen", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        year: "Mar 23, 2023",
        image: "/img-2.jpg"
      },
      { 
        id: 3, 
        name: "5 Songs That Make Me REALLY Happy", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        year: "Mar 23,2023",
        image: "/img-3.jpg"
      },
      { 
        id: 4, 
        name: "Amsterdam 101: Redefining The French Fries", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        price: 200,
        image: "/img-4.jpg"
      },
      { 
        id: 5, 
        name: "Turkey: Unique Festivals You Must Visit", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        price: 250,
        image: "/img-5.jpg"
      },
      { 
        id: 6, 
        name: "Paris: Secrets Only The Locals Can Tell You", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        price: 300,
        image: "/img-6.jpg"
      },
      { 
        id: 7, 
        name: "Back to Fiction: What I'm Reading This Summer", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        price: 450,
        image: "/img-7.jpg"
      },
      { 
        id: 8, 
        name: "Best Podcasts to Listen to When Traveling", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.Create a blog post subtitle that summarizes your post in a few short, punchy sentences and...", 
        price: 350,
        image: "/img-8.jpg"
      },
      { 
        id: 9, 
        name: "This is Umehani, the creater of this blog website.", 
        description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.click the blog and know me more...", 
        year: "Dec 24, 2024",
        image: "/img-10.jpg"
      },
      { 
          id: 10, 
          name: "I love to travel ...", 
          description: "A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself.click the blog and know me more...", 
          year: "Dec 24, 2024",
          image: "/img-7.jpg"
        },
        { 
          id: 11, 
          name: "I love to travel ...", 
          description: "click the blog and know me more A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself....", 
          year: "Dec 24, 2024",
          image: "/img-8.jpg"
        },
        { 
          id: 12, 
          name: "I love to travel ...", 
          description: "click the blog and know me more A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself. A Season of Exploration Summer offers the perfect opportunity to dive into the world of books. With its long, sunny days and a relaxed pace, it’s an ideal season to indulge in reading, whether you're stretched out on a beach towel, lounging in a hammock, or nestled in a cozy corner at home. The warm weather often inspires readers to explore genres that align with the season—lighthearted romances, gripping thrillers, or travelogues that whisk you away to exotic locales. Summer reading doesn’t just entertain; it also stimulates the mind and provides an escape from the heat of the day. For students and lifelong learners, summer reading can be an enriching way to build new skills or delve deeper into personal interests. Many schools and libraries host summer reading programs to encourage reading habits in children, helping them retain knowledge during the break. For adults, this is the time to tackle that ever-growing to-be-read list or join book clubs to share literary adventures with others. Beyond the intellectual benefits, reading in summer has an unmatched charm. The combination of vibrant settings and engaging narratives often creates memories as cherished as the stories themselves. Whether you’re re-reading an old favorite or discovering a new gem, summer transforms reading into an experience as refreshing and uplifting as the season itself....", 
          year: "Dec 24, 2024",
          image: "/img-9.jpg"
        },
      
  ];

export default function Blog() {
  const params = useParams(); 
  const id = params?.id as string; 

  const blogId = id ? parseInt(id, 10) : null; 
  const blog = blogs.find((item) => item.id === blogId); 

  if (!blog) {
    return <p className="text-center mt-10">Blog not found.</p>;
  }


  
    const [products, setProducts] = useState([
      { id: 9, quantity: 1 },
    ]);
  
    // Handle adding quantity
    const increaseQuantity = (id: number) => {
      setProducts((prevProducts) =>
        prevProducts.map((product) =>
          product.id === id
            ? { ...product, quantity: product.quantity + 1 }
            : product
        )
      );
    };

    

  return (
    <div>
      <Navigation/>
      <div className="pt-10 pb-10 mx-10 md:mx-40">
      <div className="flex border border-black">
      {blog.image && (
          <Image
            src={blog.image}
            alt={blog.name || "blog Image"}
            width={500}
            height={300}
            className=""
          />
        )}
        <div className="container md:w-[600px] text-justify  md:px-10">
        <h1 className="text-2xl font-bold pt-5">{blog.name}</h1>
        <p className="text-gray-500 font-light text-xs pt-5 ">{blog.year}</p>
        
        <hr/>
        <p className="flex gap-5 text-gray-500 text-xs font-light pt-5 pb-5 items-center">
                    0 Views <span className="px-5"> 0 Comments</span>
             
        {products.map((product) => (
            
            <div className="flex items-center text-lg">
                <Button className="bg-transparent shadow-none hover:bg-transparent"
                  onClick={() => increaseQuantity(product.id)}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="red" stroke="#ff0000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-heart hover:fill-red-600"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>
                </Button>
                {product.quantity}
              </div>
          ))}
          </p>
        </div>
      </div>
      <p className="text-gray-700 pt-10 text-sm leading-10 text-justify pb-5 ">{blog.description}</p>
      </div>


      
      <hr/>
      <Footer/>
    </div>

  );
}
